# Generated by Django 5.1.5 on 2025-02-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=10)),
                ('area_n', models.CharField(max_length=255)),
                ('solicitud', models.CharField(max_length=10)),
                ('solicitud_n', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('detalle', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=10)),
                ('responsable_n', models.CharField(max_length=255)),
                ('asignar', models.CharField(max_length=10)),
                ('asignar_a_n', models.CharField(max_length=255)),
                ('adjunto', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('usuario_solicitud', models.CharField(max_length=255)),
                ('usuario_solicitud_n', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField()),
                ('adjunto_cierre', models.CharField(max_length=255)),
            ],
        ),
    ]
