# Generated by Django 5.1.5 on 2025-02-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sispa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOLICITUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rel', models.CharField(max_length=10)),
                ('solicitud', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
